feat(go): adds generated Go code and changes the pakage name.
hypertrace/agent-config pull request #50
Opened 2021-02-10 08:05 UTC by jcchavezs

## Description

Currently we publish the proto file but not the generated code, transferring that responsibility to client libraries. While that works, it is impossible to make it portable for example when a library wants to compose the agent config with something else (because the generated code will have a different package fqn). Publishing the config object makes it easy to compose config.

### Checklist:
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules

2021-02-10 16:55 UTC, davexroth approved these changes

2021-02-11 10:24 UTC, pavolloffay commented
>  While that works, it is impossible to make it portable for example when a library wants to compose the agent config with something else (because the generated code will have a different package fqn). 

If we changed go package in proto to (from https://github.com/hypertrace/agent-config/pull/48)
```
from: option go_package = "github.com/hypertrace/agent-config/config";
to: option go_package = "github.com/hypertrace/goagent/config";
``` 

would it be a problem/would this PR be needed? Java package points as well to java agent package https://github.com/hypertrace/agent-config/blob/main/config.proto#L8. 

Now we will split generated files into multiple projects - java in javaagent, go here... The idea was to host the config in client libraries to avoid multi lang publishing in a single repository and tight language-specific defaults with the config.

2021-02-15 05:29 UTC, jcchavezs commented
@pavolloffayI think the current issue is languages vs libraries. If we assume/decide every go library consuming this config package will use the goagent then it is fine to bring back #48. If not, we need to apply this.

2021-02-15 08:06 UTC, mohit-a21 requested changes

2021-02-15 08:06 UTC, mohit-a21 commented on Makefile
> +	@protoc --go_out=paths=source_relative:. config.proto
Can we use buf tool to generate code here instead of protoc?

2021-02-16 04:15 UTC, closed without merging